@startuml thing_input

Lambda <-- Thing: { "MeasurementTemperature": { "id": "1", "temperature": 19.51111 } }
Lambda <-- Thing: { "MeasurmentHumidity": { "id": "1", "humidity": 46 } }

' APIGateway --> Thing: { "SetName": { "id": "1", "name": "new_thing" } }
APIGateway --> Thing: { "LampState": { "id": "1", "state": true/false } }
APIGateway --> Thing: { "LampRGB": { "id": "1", "r": 1, "g": 2, "b": 3 } }

@enduml
